/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItemCategory = IDL.Variant({
  'ceramic' : IDL.Null,
  'printed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BulkItemInput = IDL.Record({
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'category' : ItemCategory,
  'shapeCategory' : IDL.Text,
  'photo' : ExternalBlob,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Item = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'published' : IDL.Bool,
  'createdBy' : IDL.Principal,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ItemCategory,
  'shapeCategory' : IDL.Text,
  'photo' : ExternalBlob,
  'priceInCents' : IDL.Nat,
});
export const StorefrontHeroText = IDL.Variant({
  'custom' : IDL.Record({ 'title' : IDL.Text, 'subtitle' : IDL.Text }),
  'default' : IDL.Null,
});
export const MediaKind = IDL.Variant({
  'image' : IDL.Null,
  'model3d' : IDL.Record({ 'modelType' : IDL.Text }),
});
export const BrandingAsset = IDL.Record({
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'mediaKind' : MediaKind,
});
export const Branding = IDL.Record({
  'appName' : IDL.Text,
  'logo' : ExternalBlob,
  'storefrontHeroText' : StorefrontHeroText,
  'heroMedia' : BrandingAsset,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StorefrontItems = IDL.Record({
  'headerAsset' : BrandingAsset,
  'heroText' : StorefrontHeroText,
  'items' : IDL.Vec(Item),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShapeCategory' : IDL.Func([IDL.Text], [], []),
  'addToBasket' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUploadItems' : IDL.Func(
      [IDL.Vec(BulkItemInput)],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
    ),
  'clearBasket' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCheckoutSessionFromBasket' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getBasket' : IDL.Func(
      [],
      [
        IDL.Record({
          'items' : IDL.Vec(Item),
          'itemIds' : IDL.Vec(IDL.Vec(IDL.Nat8)),
        }),
      ],
      ['query'],
    ),
  'getBranding' : IDL.Func([], [IDL.Opt(Branding)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Vec(IDL.Nat8)], [Item], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
  'getShapeCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStorefrontHeroText' : IDL.Func([], [StorefrontHeroText], ['query']),
  'getStorefrontItems' : IDL.Func([], [IDL.Opt(StorefrontItems)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markItemsAsSold' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
  'publishItems' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
  'removeFromBasket' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'renameShapeCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBranding' : IDL.Func([Branding], [], []),
  'setItemPrice' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Nat], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishItems' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
  'updateAllItemPricesByCategory' : IDL.Func([], [], []),
  'updateAllPrintedItemDescriptions' : IDL.Func([IDL.Text], [], []),
  'updateItemDescription' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  'updateItemPhoto' : IDL.Func(
      [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItemCategory = IDL.Variant({
    'ceramic' : IDL.Null,
    'printed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BulkItemInput = IDL.Record({
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'category' : ItemCategory,
    'shapeCategory' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Item = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'published' : IDL.Bool,
    'createdBy' : IDL.Principal,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ItemCategory,
    'shapeCategory' : IDL.Text,
    'photo' : ExternalBlob,
    'priceInCents' : IDL.Nat,
  });
  const StorefrontHeroText = IDL.Variant({
    'custom' : IDL.Record({ 'title' : IDL.Text, 'subtitle' : IDL.Text }),
    'default' : IDL.Null,
  });
  const MediaKind = IDL.Variant({
    'image' : IDL.Null,
    'model3d' : IDL.Record({ 'modelType' : IDL.Text }),
  });
  const BrandingAsset = IDL.Record({
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'mediaKind' : MediaKind,
  });
  const Branding = IDL.Record({
    'appName' : IDL.Text,
    'logo' : ExternalBlob,
    'storefrontHeroText' : StorefrontHeroText,
    'heroMedia' : BrandingAsset,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StorefrontItems = IDL.Record({
    'headerAsset' : BrandingAsset,
    'heroText' : StorefrontHeroText,
    'items' : IDL.Vec(Item),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShapeCategory' : IDL.Func([IDL.Text], [], []),
    'addToBasket' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUploadItems' : IDL.Func(
        [IDL.Vec(BulkItemInput)],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
      ),
    'clearBasket' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCheckoutSessionFromBasket' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getBasket' : IDL.Func(
        [],
        [
          IDL.Record({
            'items' : IDL.Vec(Item),
            'itemIds' : IDL.Vec(IDL.Vec(IDL.Nat8)),
          }),
        ],
        ['query'],
      ),
    'getBranding' : IDL.Func([], [IDL.Opt(Branding)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Vec(IDL.Nat8)], [Item], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
    'getShapeCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStorefrontHeroText' : IDL.Func([], [StorefrontHeroText], ['query']),
    'getStorefrontItems' : IDL.Func([], [IDL.Opt(StorefrontItems)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markItemsAsSold' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
    'publishItems' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
    'removeFromBasket' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'renameShapeCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBranding' : IDL.Func([Branding], [], []),
    'setItemPrice' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Nat], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishItems' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
    'updateAllItemPricesByCategory' : IDL.Func([], [], []),
    'updateAllPrintedItemDescriptions' : IDL.Func([IDL.Text], [], []),
    'updateItemDescription' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'updateItemPhoto' : IDL.Func(
        [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };