/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branding {
  'appName' : string,
  'logo' : ExternalBlob,
  'storefrontHeroText' : StorefrontHeroText,
  'heroMedia' : BrandingAsset,
}
export interface BrandingAsset {
  'contentType' : string,
  'blob' : ExternalBlob,
  'mediaKind' : MediaKind,
}
export interface BulkItemInput {
  'title' : string,
  'contentType' : string,
  'description' : [] | [string],
  'category' : ItemCategory,
  'shapeCategory' : string,
  'photo' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface Item {
  'id' : Uint8Array,
  'title' : string,
  'contentType' : string,
  'published' : boolean,
  'createdBy' : Principal,
  'sold' : boolean,
  'description' : string,
  'category' : ItemCategory,
  'shapeCategory' : string,
  'photo' : ExternalBlob,
  'priceInCents' : bigint,
}
export type ItemCategory = { 'ceramic' : null } |
  { 'printed' : null };
export type MediaKind = { 'image' : null } |
  { 'model3d' : { 'modelType' : string } };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type StorefrontHeroText = {
    'custom' : { 'title' : string, 'subtitle' : string }
  } |
  { 'default' : null };
export interface StorefrontItems {
  'headerAsset' : BrandingAsset,
  'heroText' : StorefrontHeroText,
  'items' : Array<Item>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addShapeCategory' : ActorMethod<[string], undefined>,
  'addToBasket' : ActorMethod<[Uint8Array], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadItems' : ActorMethod<[Array<BulkItemInput>], Array<Uint8Array>>,
  'clearBasket' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCheckoutSessionFromBasket' : ActorMethod<[string, string], string>,
  'getBasket' : ActorMethod<
    [],
    { 'items' : Array<Item>, 'itemIds' : Array<Uint8Array> }
  >,
  'getBranding' : ActorMethod<[], [] | [Branding]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItem' : ActorMethod<[Uint8Array], Item>,
  'getItems' : ActorMethod<[], Array<Item>>,
  'getItemsByCategory' : ActorMethod<[ItemCategory], Array<Item>>,
  'getShapeCategories' : ActorMethod<[], Array<string>>,
  'getStorefrontHeroText' : ActorMethod<[], StorefrontHeroText>,
  'getStorefrontItems' : ActorMethod<[], [] | [StorefrontItems]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markItemsAsSold' : ActorMethod<[Array<Uint8Array>], undefined>,
  'publishItems' : ActorMethod<[Array<Uint8Array>], undefined>,
  'removeFromBasket' : ActorMethod<[Uint8Array], undefined>,
  'renameShapeCategory' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBranding' : ActorMethod<[Branding], undefined>,
  'setItemPrice' : ActorMethod<[Uint8Array, bigint], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishItems' : ActorMethod<[Array<Uint8Array>], undefined>,
  'updateAllItemPricesByCategory' : ActorMethod<[], undefined>,
  'updateAllPrintedItemDescriptions' : ActorMethod<[string], undefined>,
  'updateItemDescription' : ActorMethod<[Uint8Array, string], undefined>,
  'updateItemPhoto' : ActorMethod<
    [Uint8Array, ExternalBlob, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];